### ISSUE TITLE
CSS files do not have line wraps in GitHub code viewer

### ISSUE THREAD

**Issue by DanRathbun** [SketchUp/sketchup-yard-template#9]
CSS files do not have line wraps in GitHub code viewer.

Files infolder:
`/su-template/default/fulldoc/html/css/`

**Comment by thomthom** [comment]
Some of the files are automatically generated and minified. (They should relate to the SketchUp header I think.)

Any file in particular? Or any element in particular you where looking for?

**Comment by DanRathbun** [comment]
There are only 2 files in that folder.

At the time, I was looking to see if your template had modified the `div#search` style rule.

Since they are minified (or "un-linefeed-ified") it is very hard to read them to know.

> @thomthom: (They should relate to the SketchUp header I think.)

If this is true, and only these OEM stylesheets will be minified, then that's alright.
I just found it weird that you'd post a project, and ask ppl to clone&PR, with obfuscated files.

I thought perhaps the file were using EOLs that the GitHub code viewer didn't like.

**Comment by thomthom** [comment]
The API docs were made before we figured out we could start accepting pull request for this.

I think Chrome's Developer Tools have some feature to prettyfi CSS. At least it will let you see all the styles it uses.

**Comment by thomthom** [comment]
Found it: http://stackoverflow.com/a/33731704

![image](https://cloud.githubusercontent.com/assets/192418/22028443/6cd028be-dc94-11e6-806a-503bdcfd2d2f.png)

**Comment by DanRathbun** [comment]
> I think Chrome's Developer Tools have some feature to prettyfi CSS. At least it will let you see all the styles it uses.

Thanx, Tried it, it works. (Now to remember.) **Closing this issue.**
